"""
    CarbonAware.WebApi

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.emissions_forecast_batch_parameters_dto import EmissionsForecastBatchParametersDTO


class TestEmissionsForecastBatchParametersDTO(unittest.TestCase):
    """EmissionsForecastBatchParametersDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEmissionsForecastBatchParametersDTO(self):
        """Test EmissionsForecastBatchParametersDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EmissionsForecastBatchParametersDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
