# flake8: noqa

"""
    CarbonAware.WebApi

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from carbon_sdk_client.openapi_client.api_client import ApiClient

# import Configuration
from carbon_sdk_client.openapi_client.configuration import Configuration

# import exceptions
from carbon_sdk_client.openapi_client.exceptions import OpenApiException
from carbon_sdk_client.openapi_client.exceptions import ApiAttributeError
from carbon_sdk_client.openapi_client.exceptions import ApiTypeError
from carbon_sdk_client.openapi_client.exceptions import ApiValueError
from carbon_sdk_client.openapi_client.exceptions import ApiKeyError
from carbon_sdk_client.openapi_client.exceptions import ApiException
